#!/usr/bin/env bash

# Update the system clock
#timedatectl set-ntp true

# Get hostname
#hostname=$(dialog --stdout --inputbox "Enter hostname" 0 0) || exit 1
#: ${hostname:?"non-empty value must be entered"}

partitionsCorrect=false
until [ "$partitionsChosen" = false ]
do
    # Get partitions
    readarray -t rawLsblk < <(lsblk -nlo NAME,SIZE,TYPE,MOUNTPOINT | awk '/part/')
    COLUMNS=0 # ensure each option is printed on its own line
    PS3='Select root partition: '
    select partition in "${rawLsblk[@]}"
    do
        [[ -n $partition ]] || { echo "Invalid choice. Please try again." >&2; continue; }
        break # valid choice was made; exit prompt.
    done
    echo

    # Isolate root partition name
    rootPartition=$(echo $partition | cut -d ' ' -f1)

    PS3='Select swap partition: '
    select partition in "${rawLsblk[@]}"
    do
        ([[ -n $partition ]] || { echo "Invalid choice. Please try again." >&2; continue; }) && ([[ $partition != $rootPartition ]] || { echo "Partition already chosen to be root. Please try again." >&2; continue; })
        break # valid choice was made; exit prompt.
    done
    echo



done
# Isolate swap partition name
swapPartition=$(echo $partition | cut -d ' ' -f1)

# Get root and swap partitions
#partitionRoot=$(dialog --stdout --treeview "Select a root partition" 0 0 0 "$partitionTags") || exit 1
#: ${paritionRoot:?"non-empty value must be entered"}
#echo $partitionRoot
